### ISSUE TITLE
AndroidX 

### ISSUE THREAD

**Issue by fgh345** [CaiJingLong/flutter_gps#1]
Please provide no use Androidx .
Problems with my project:
Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution

And I can't upgrade Androidx

**Comment by CaiJingLong** [comment]
AndroidX is used to facilitate coding. If it causes conflicts in your plug-ins, you can use the following two ways:
1. Fork works by modifying the Android X version of gradle and then using [git dependencies](https://dart.dev/tools/pub/dependencies#git-packages).
2. Use a similar approach in gradle scripts to avoid conflicts

```groovy
rootProject.allprojects {

    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.github.bumptech.glide' //Replace to your conflict org name.
                        && details.requested.name.contains('glide')) { // Replace to your conflict library name.
                    details.useVersion "4.9.0" // Replace to your need version.
                }
            }
        }
    }
}
```

**Comment by fgh345** [comment]
非常感谢




------------------ 原始邮件 ------------------
发件人: "Caijinglong"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 下午3:53
收件人: "CaiJingLong/flutter_gps"<flutter_gps@noreply.github.com>;
抄送: "君值韶华莫等闲"<1145073867@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CaiJingLong/flutter_gps] AndroidX  (#1)




AndroidX is used to facilitate coding. If it causes conflicts in your plug-ins, you can use the following two ways:
  
Fork works by modifying the Android X version of gradle and then using git dependencies.
 
Use a similar approach in gradle scripts to avoid conflicts
  rootProject.allprojects {     subprojects {         project.configurations.all {             resolutionStrategy.eachDependency { details ->                 if (details.requested.group == 'com.github.bumptech.glide' //Replace to your conflict org name.                         && details.requested.name.contains('glide')) { // Replace to your conflict library name.                     details.useVersion "4.9.0" // Replace to your need version.                 }             }         }     } }
